// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geo-proto.proto

package edu.umn.cse.geoproto;

public final class GeoProto {
  private GeoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code edu.umn.cse.geoproto.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FeatureCollection = 0;</code>
     */
    FeatureCollection(0),
    /**
     * <code>Feature = 1;</code>
     */
    Feature(1),
    /**
     * <code>Geometry = 2;</code>
     */
    Geometry(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>FeatureCollection = 0;</code>
     */
    public static final int FeatureCollection_VALUE = 0;
    /**
     * <code>Feature = 1;</code>
     */
    public static final int Feature_VALUE = 1;
    /**
     * <code>Geometry = 2;</code>
     */
    public static final int Geometry_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    public static Type forNumber(int value) {
      switch (value) {
        case 0: return FeatureCollection;
        case 1: return Feature;
        case 2: return Geometry;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return edu.umn.cse.geoproto.GeoProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:edu.umn.cse.geoproto.Type)
  }

  /**
   * Protobuf enum {@code edu.umn.cse.geoproto.GeometryType}
   */
  public enum GeometryType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Point = 0;</code>
     */
    Point(0),
    /**
     * <code>LineString = 1;</code>
     */
    LineString(1),
    /**
     * <code>Polygon = 2;</code>
     */
    Polygon(2),
    /**
     * <code>MultiPoint = 3;</code>
     */
    MultiPoint(3),
    /**
     * <code>MultiLineString = 4;</code>
     */
    MultiLineString(4),
    /**
     * <code>MultiPolygon = 5;</code>
     */
    MultiPolygon(5),
    /**
     * <code>GeometryCollection = 6;</code>
     */
    GeometryCollection(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Point = 0;</code>
     */
    public static final int Point_VALUE = 0;
    /**
     * <code>LineString = 1;</code>
     */
    public static final int LineString_VALUE = 1;
    /**
     * <code>Polygon = 2;</code>
     */
    public static final int Polygon_VALUE = 2;
    /**
     * <code>MultiPoint = 3;</code>
     */
    public static final int MultiPoint_VALUE = 3;
    /**
     * <code>MultiLineString = 4;</code>
     */
    public static final int MultiLineString_VALUE = 4;
    /**
     * <code>MultiPolygon = 5;</code>
     */
    public static final int MultiPolygon_VALUE = 5;
    /**
     * <code>GeometryCollection = 6;</code>
     */
    public static final int GeometryCollection_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static GeometryType valueOf(int value) {
      return forNumber(value);
    }

    public static GeometryType forNumber(int value) {
      switch (value) {
        case 0: return Point;
        case 1: return LineString;
        case 2: return Polygon;
        case 3: return MultiPoint;
        case 4: return MultiLineString;
        case 5: return MultiPolygon;
        case 6: return GeometryCollection;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GeometryType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GeometryType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GeometryType>() {
            public GeometryType findValueByNumber(int number) {
              return GeometryType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return edu.umn.cse.geoproto.GeoProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final GeometryType[] VALUES = values();

    public static GeometryType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GeometryType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:edu.umn.cse.geoproto.GeometryType)
  }

  public interface FeatureCollectionMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:edu.umn.cse.geoproto.FeatureCollectionMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.edu.umn.cse.geoproto.Type type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.edu.umn.cse.geoproto.Type type = 1;</code>
     */
    edu.umn.cse.geoproto.GeoProto.Type getType();

    /**
     * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
     */
    java.util.List<edu.umn.cse.geoproto.GeoProto.FeatureMsg> 
        getFeaturesList();
    /**
     * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
     */
    edu.umn.cse.geoproto.GeoProto.FeatureMsg getFeatures(int index);
    /**
     * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
     */
    int getFeaturesCount();
    /**
     * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
     */
    java.util.List<? extends edu.umn.cse.geoproto.GeoProto.FeatureMsgOrBuilder> 
        getFeaturesOrBuilderList();
    /**
     * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
     */
    edu.umn.cse.geoproto.GeoProto.FeatureMsgOrBuilder getFeaturesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code edu.umn.cse.geoproto.FeatureCollectionMsg}
   */
  public  static final class FeatureCollectionMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:edu.umn.cse.geoproto.FeatureCollectionMsg)
      FeatureCollectionMsgOrBuilder {
    // Use FeatureCollectionMsg.newBuilder() to construct.
    private FeatureCollectionMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FeatureCollectionMsg() {
      type_ = 0;
      features_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private FeatureCollectionMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                features_ = new java.util.ArrayList<edu.umn.cse.geoproto.GeoProto.FeatureMsg>();
                mutable_bitField0_ |= 0x00000002;
              }
              features_.add(
                  input.readMessage(edu.umn.cse.geoproto.GeoProto.FeatureMsg.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          features_ = java.util.Collections.unmodifiableList(features_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umn.cse.geoproto.GeoProto.internal_static_edu_umn_cse_geoproto_FeatureCollectionMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umn.cse.geoproto.GeoProto.internal_static_edu_umn_cse_geoproto_FeatureCollectionMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg.class, edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.edu.umn.cse.geoproto.Type type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.edu.umn.cse.geoproto.Type type = 1;</code>
     */
    public edu.umn.cse.geoproto.GeoProto.Type getType() {
      edu.umn.cse.geoproto.GeoProto.Type result = edu.umn.cse.geoproto.GeoProto.Type.valueOf(type_);
      return result == null ? edu.umn.cse.geoproto.GeoProto.Type.UNRECOGNIZED : result;
    }

    public static final int FEATURES_FIELD_NUMBER = 2;
    private java.util.List<edu.umn.cse.geoproto.GeoProto.FeatureMsg> features_;
    /**
     * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
     */
    public java.util.List<edu.umn.cse.geoproto.GeoProto.FeatureMsg> getFeaturesList() {
      return features_;
    }
    /**
     * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
     */
    public java.util.List<? extends edu.umn.cse.geoproto.GeoProto.FeatureMsgOrBuilder> 
        getFeaturesOrBuilderList() {
      return features_;
    }
    /**
     * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
     */
    public int getFeaturesCount() {
      return features_.size();
    }
    /**
     * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
     */
    public edu.umn.cse.geoproto.GeoProto.FeatureMsg getFeatures(int index) {
      return features_.get(index);
    }
    /**
     * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
     */
    public edu.umn.cse.geoproto.GeoProto.FeatureMsgOrBuilder getFeaturesOrBuilder(
        int index) {
      return features_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != edu.umn.cse.geoproto.GeoProto.Type.FeatureCollection.getNumber()) {
        output.writeEnum(1, type_);
      }
      for (int i = 0; i < features_.size(); i++) {
        output.writeMessage(2, features_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != edu.umn.cse.geoproto.GeoProto.Type.FeatureCollection.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      for (int i = 0; i < features_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, features_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg)) {
        return super.equals(obj);
      }
      edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg other = (edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getFeaturesList()
          .equals(other.getFeaturesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (getFeaturesCount() > 0) {
        hash = (37 * hash) + FEATURES_FIELD_NUMBER;
        hash = (53 * hash) + getFeaturesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu.umn.cse.geoproto.FeatureCollectionMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:edu.umn.cse.geoproto.FeatureCollectionMsg)
        edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.umn.cse.geoproto.GeoProto.internal_static_edu_umn_cse_geoproto_FeatureCollectionMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.umn.cse.geoproto.GeoProto.internal_static_edu_umn_cse_geoproto_FeatureCollectionMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg.class, edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg.Builder.class);
      }

      // Construct using edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFeaturesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        if (featuresBuilder_ == null) {
          features_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          featuresBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umn.cse.geoproto.GeoProto.internal_static_edu_umn_cse_geoproto_FeatureCollectionMsg_descriptor;
      }

      public edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg getDefaultInstanceForType() {
        return edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg.getDefaultInstance();
      }

      public edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg build() {
        edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg buildPartial() {
        edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg result = new edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        if (featuresBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            features_ = java.util.Collections.unmodifiableList(features_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.features_ = features_;
        } else {
          result.features_ = featuresBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg) {
          return mergeFrom((edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg other) {
        if (other == edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (featuresBuilder_ == null) {
          if (!other.features_.isEmpty()) {
            if (features_.isEmpty()) {
              features_ = other.features_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureFeaturesIsMutable();
              features_.addAll(other.features_);
            }
            onChanged();
          }
        } else {
          if (!other.features_.isEmpty()) {
            if (featuresBuilder_.isEmpty()) {
              featuresBuilder_.dispose();
              featuresBuilder_ = null;
              features_ = other.features_;
              bitField0_ = (bitField0_ & ~0x00000002);
              featuresBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFeaturesFieldBuilder() : null;
            } else {
              featuresBuilder_.addAllMessages(other.features_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.edu.umn.cse.geoproto.Type type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.edu.umn.cse.geoproto.Type type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.edu.umn.cse.geoproto.Type type = 1;</code>
       */
      public edu.umn.cse.geoproto.GeoProto.Type getType() {
        edu.umn.cse.geoproto.GeoProto.Type result = edu.umn.cse.geoproto.GeoProto.Type.valueOf(type_);
        return result == null ? edu.umn.cse.geoproto.GeoProto.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.edu.umn.cse.geoproto.Type type = 1;</code>
       */
      public Builder setType(edu.umn.cse.geoproto.GeoProto.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.edu.umn.cse.geoproto.Type type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<edu.umn.cse.geoproto.GeoProto.FeatureMsg> features_ =
        java.util.Collections.emptyList();
      private void ensureFeaturesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          features_ = new java.util.ArrayList<edu.umn.cse.geoproto.GeoProto.FeatureMsg>(features_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          edu.umn.cse.geoproto.GeoProto.FeatureMsg, edu.umn.cse.geoproto.GeoProto.FeatureMsg.Builder, edu.umn.cse.geoproto.GeoProto.FeatureMsgOrBuilder> featuresBuilder_;

      /**
       * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
       */
      public java.util.List<edu.umn.cse.geoproto.GeoProto.FeatureMsg> getFeaturesList() {
        if (featuresBuilder_ == null) {
          return java.util.Collections.unmodifiableList(features_);
        } else {
          return featuresBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
       */
      public int getFeaturesCount() {
        if (featuresBuilder_ == null) {
          return features_.size();
        } else {
          return featuresBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
       */
      public edu.umn.cse.geoproto.GeoProto.FeatureMsg getFeatures(int index) {
        if (featuresBuilder_ == null) {
          return features_.get(index);
        } else {
          return featuresBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
       */
      public Builder setFeatures(
          int index, edu.umn.cse.geoproto.GeoProto.FeatureMsg value) {
        if (featuresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFeaturesIsMutable();
          features_.set(index, value);
          onChanged();
        } else {
          featuresBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
       */
      public Builder setFeatures(
          int index, edu.umn.cse.geoproto.GeoProto.FeatureMsg.Builder builderForValue) {
        if (featuresBuilder_ == null) {
          ensureFeaturesIsMutable();
          features_.set(index, builderForValue.build());
          onChanged();
        } else {
          featuresBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
       */
      public Builder addFeatures(edu.umn.cse.geoproto.GeoProto.FeatureMsg value) {
        if (featuresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFeaturesIsMutable();
          features_.add(value);
          onChanged();
        } else {
          featuresBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
       */
      public Builder addFeatures(
          int index, edu.umn.cse.geoproto.GeoProto.FeatureMsg value) {
        if (featuresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFeaturesIsMutable();
          features_.add(index, value);
          onChanged();
        } else {
          featuresBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
       */
      public Builder addFeatures(
          edu.umn.cse.geoproto.GeoProto.FeatureMsg.Builder builderForValue) {
        if (featuresBuilder_ == null) {
          ensureFeaturesIsMutable();
          features_.add(builderForValue.build());
          onChanged();
        } else {
          featuresBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
       */
      public Builder addFeatures(
          int index, edu.umn.cse.geoproto.GeoProto.FeatureMsg.Builder builderForValue) {
        if (featuresBuilder_ == null) {
          ensureFeaturesIsMutable();
          features_.add(index, builderForValue.build());
          onChanged();
        } else {
          featuresBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
       */
      public Builder addAllFeatures(
          java.lang.Iterable<? extends edu.umn.cse.geoproto.GeoProto.FeatureMsg> values) {
        if (featuresBuilder_ == null) {
          ensureFeaturesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, features_);
          onChanged();
        } else {
          featuresBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
       */
      public Builder clearFeatures() {
        if (featuresBuilder_ == null) {
          features_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          featuresBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
       */
      public Builder removeFeatures(int index) {
        if (featuresBuilder_ == null) {
          ensureFeaturesIsMutable();
          features_.remove(index);
          onChanged();
        } else {
          featuresBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
       */
      public edu.umn.cse.geoproto.GeoProto.FeatureMsg.Builder getFeaturesBuilder(
          int index) {
        return getFeaturesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
       */
      public edu.umn.cse.geoproto.GeoProto.FeatureMsgOrBuilder getFeaturesOrBuilder(
          int index) {
        if (featuresBuilder_ == null) {
          return features_.get(index);  } else {
          return featuresBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
       */
      public java.util.List<? extends edu.umn.cse.geoproto.GeoProto.FeatureMsgOrBuilder> 
           getFeaturesOrBuilderList() {
        if (featuresBuilder_ != null) {
          return featuresBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(features_);
        }
      }
      /**
       * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
       */
      public edu.umn.cse.geoproto.GeoProto.FeatureMsg.Builder addFeaturesBuilder() {
        return getFeaturesFieldBuilder().addBuilder(
            edu.umn.cse.geoproto.GeoProto.FeatureMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
       */
      public edu.umn.cse.geoproto.GeoProto.FeatureMsg.Builder addFeaturesBuilder(
          int index) {
        return getFeaturesFieldBuilder().addBuilder(
            index, edu.umn.cse.geoproto.GeoProto.FeatureMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .edu.umn.cse.geoproto.FeatureMsg features = 2;</code>
       */
      public java.util.List<edu.umn.cse.geoproto.GeoProto.FeatureMsg.Builder> 
           getFeaturesBuilderList() {
        return getFeaturesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          edu.umn.cse.geoproto.GeoProto.FeatureMsg, edu.umn.cse.geoproto.GeoProto.FeatureMsg.Builder, edu.umn.cse.geoproto.GeoProto.FeatureMsgOrBuilder> 
          getFeaturesFieldBuilder() {
        if (featuresBuilder_ == null) {
          featuresBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              edu.umn.cse.geoproto.GeoProto.FeatureMsg, edu.umn.cse.geoproto.GeoProto.FeatureMsg.Builder, edu.umn.cse.geoproto.GeoProto.FeatureMsgOrBuilder>(
                  features_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          features_ = null;
        }
        return featuresBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:edu.umn.cse.geoproto.FeatureCollectionMsg)
    }

    // @@protoc_insertion_point(class_scope:edu.umn.cse.geoproto.FeatureCollectionMsg)
    private static final edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg();
    }

    public static edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FeatureCollectionMsg>
        PARSER = new com.google.protobuf.AbstractParser<FeatureCollectionMsg>() {
      public FeatureCollectionMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FeatureCollectionMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FeatureCollectionMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FeatureCollectionMsg> getParserForType() {
      return PARSER;
    }

    public edu.umn.cse.geoproto.GeoProto.FeatureCollectionMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FeatureMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:edu.umn.cse.geoproto.FeatureMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.edu.umn.cse.geoproto.Type type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.edu.umn.cse.geoproto.Type type = 1;</code>
     */
    edu.umn.cse.geoproto.GeoProto.Type getType();

    /**
     * <code>.edu.umn.cse.geoproto.GeometryMsg geometry = 2;</code>
     */
    boolean hasGeometry();
    /**
     * <code>.edu.umn.cse.geoproto.GeometryMsg geometry = 2;</code>
     */
    edu.umn.cse.geoproto.GeoProto.GeometryMsg getGeometry();
    /**
     * <code>.edu.umn.cse.geoproto.GeometryMsg geometry = 2;</code>
     */
    edu.umn.cse.geoproto.GeoProto.GeometryMsgOrBuilder getGeometryOrBuilder();

    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */
    int getPropertiesCount();
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */
    boolean containsProperties(
        java.lang.String key);
    /**
     * Use {@link #getPropertiesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getProperties();
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getPropertiesMap();
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */

    java.lang.String getPropertiesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */

    java.lang.String getPropertiesOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code edu.umn.cse.geoproto.FeatureMsg}
   */
  public  static final class FeatureMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:edu.umn.cse.geoproto.FeatureMsg)
      FeatureMsgOrBuilder {
    // Use FeatureMsg.newBuilder() to construct.
    private FeatureMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FeatureMsg() {
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private FeatureMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              edu.umn.cse.geoproto.GeoProto.GeometryMsg.Builder subBuilder = null;
              if (geometry_ != null) {
                subBuilder = geometry_.toBuilder();
              }
              geometry_ = input.readMessage(edu.umn.cse.geoproto.GeoProto.GeometryMsg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(geometry_);
                geometry_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                properties_ = com.google.protobuf.MapField.newMapField(
                    PropertiesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              properties__ = input.readMessage(
                  PropertiesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              properties_.getMutableMap().put(
                  properties__.getKey(), properties__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umn.cse.geoproto.GeoProto.internal_static_edu_umn_cse_geoproto_FeatureMsg_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetProperties();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umn.cse.geoproto.GeoProto.internal_static_edu_umn_cse_geoproto_FeatureMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.umn.cse.geoproto.GeoProto.FeatureMsg.class, edu.umn.cse.geoproto.GeoProto.FeatureMsg.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.edu.umn.cse.geoproto.Type type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.edu.umn.cse.geoproto.Type type = 1;</code>
     */
    public edu.umn.cse.geoproto.GeoProto.Type getType() {
      edu.umn.cse.geoproto.GeoProto.Type result = edu.umn.cse.geoproto.GeoProto.Type.valueOf(type_);
      return result == null ? edu.umn.cse.geoproto.GeoProto.Type.UNRECOGNIZED : result;
    }

    public static final int GEOMETRY_FIELD_NUMBER = 2;
    private edu.umn.cse.geoproto.GeoProto.GeometryMsg geometry_;
    /**
     * <code>.edu.umn.cse.geoproto.GeometryMsg geometry = 2;</code>
     */
    public boolean hasGeometry() {
      return geometry_ != null;
    }
    /**
     * <code>.edu.umn.cse.geoproto.GeometryMsg geometry = 2;</code>
     */
    public edu.umn.cse.geoproto.GeoProto.GeometryMsg getGeometry() {
      return geometry_ == null ? edu.umn.cse.geoproto.GeoProto.GeometryMsg.getDefaultInstance() : geometry_;
    }
    /**
     * <code>.edu.umn.cse.geoproto.GeometryMsg geometry = 2;</code>
     */
    public edu.umn.cse.geoproto.GeoProto.GeometryMsgOrBuilder getGeometryOrBuilder() {
      return getGeometry();
    }

    public static final int PROPERTIES_FIELD_NUMBER = 3;
    private static final class PropertiesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  edu.umn.cse.geoproto.GeoProto.internal_static_edu_umn_cse_geoproto_FeatureMsg_PropertiesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> properties_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetProperties() {
      if (properties_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PropertiesDefaultEntryHolder.defaultEntry);
      }
      return properties_;
    }

    public int getPropertiesCount() {
      return internalGetProperties().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */

    public boolean containsProperties(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetProperties().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPropertiesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getProperties() {
      return getPropertiesMap();
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getPropertiesMap() {
      return internalGetProperties().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */

    public java.lang.String getPropertiesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetProperties().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */

    public java.lang.String getPropertiesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetProperties().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != edu.umn.cse.geoproto.GeoProto.Type.FeatureCollection.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (geometry_ != null) {
        output.writeMessage(2, getGeometry());
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetProperties(),
          PropertiesDefaultEntryHolder.defaultEntry,
          3);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != edu.umn.cse.geoproto.GeoProto.Type.FeatureCollection.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (geometry_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getGeometry());
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetProperties().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        properties__ = PropertiesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, properties__);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.umn.cse.geoproto.GeoProto.FeatureMsg)) {
        return super.equals(obj);
      }
      edu.umn.cse.geoproto.GeoProto.FeatureMsg other = (edu.umn.cse.geoproto.GeoProto.FeatureMsg) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && (hasGeometry() == other.hasGeometry());
      if (hasGeometry()) {
        result = result && getGeometry()
            .equals(other.getGeometry());
      }
      result = result && internalGetProperties().equals(
          other.internalGetProperties());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasGeometry()) {
        hash = (37 * hash) + GEOMETRY_FIELD_NUMBER;
        hash = (53 * hash) + getGeometry().hashCode();
      }
      if (!internalGetProperties().getMap().isEmpty()) {
        hash = (37 * hash) + PROPERTIES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetProperties().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.umn.cse.geoproto.GeoProto.FeatureMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umn.cse.geoproto.GeoProto.FeatureMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umn.cse.geoproto.GeoProto.FeatureMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umn.cse.geoproto.GeoProto.FeatureMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umn.cse.geoproto.GeoProto.FeatureMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.umn.cse.geoproto.GeoProto.FeatureMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.umn.cse.geoproto.GeoProto.FeatureMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.umn.cse.geoproto.GeoProto.FeatureMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.umn.cse.geoproto.GeoProto.FeatureMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.umn.cse.geoproto.GeoProto.FeatureMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.umn.cse.geoproto.GeoProto.FeatureMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu.umn.cse.geoproto.FeatureMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:edu.umn.cse.geoproto.FeatureMsg)
        edu.umn.cse.geoproto.GeoProto.FeatureMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.umn.cse.geoproto.GeoProto.internal_static_edu_umn_cse_geoproto_FeatureMsg_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetProperties();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableProperties();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.umn.cse.geoproto.GeoProto.internal_static_edu_umn_cse_geoproto_FeatureMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.umn.cse.geoproto.GeoProto.FeatureMsg.class, edu.umn.cse.geoproto.GeoProto.FeatureMsg.Builder.class);
      }

      // Construct using edu.umn.cse.geoproto.GeoProto.FeatureMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        if (geometryBuilder_ == null) {
          geometry_ = null;
        } else {
          geometry_ = null;
          geometryBuilder_ = null;
        }
        internalGetMutableProperties().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umn.cse.geoproto.GeoProto.internal_static_edu_umn_cse_geoproto_FeatureMsg_descriptor;
      }

      public edu.umn.cse.geoproto.GeoProto.FeatureMsg getDefaultInstanceForType() {
        return edu.umn.cse.geoproto.GeoProto.FeatureMsg.getDefaultInstance();
      }

      public edu.umn.cse.geoproto.GeoProto.FeatureMsg build() {
        edu.umn.cse.geoproto.GeoProto.FeatureMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.umn.cse.geoproto.GeoProto.FeatureMsg buildPartial() {
        edu.umn.cse.geoproto.GeoProto.FeatureMsg result = new edu.umn.cse.geoproto.GeoProto.FeatureMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        if (geometryBuilder_ == null) {
          result.geometry_ = geometry_;
        } else {
          result.geometry_ = geometryBuilder_.build();
        }
        result.properties_ = internalGetProperties();
        result.properties_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umn.cse.geoproto.GeoProto.FeatureMsg) {
          return mergeFrom((edu.umn.cse.geoproto.GeoProto.FeatureMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.umn.cse.geoproto.GeoProto.FeatureMsg other) {
        if (other == edu.umn.cse.geoproto.GeoProto.FeatureMsg.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasGeometry()) {
          mergeGeometry(other.getGeometry());
        }
        internalGetMutableProperties().mergeFrom(
            other.internalGetProperties());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.umn.cse.geoproto.GeoProto.FeatureMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.umn.cse.geoproto.GeoProto.FeatureMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.edu.umn.cse.geoproto.Type type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.edu.umn.cse.geoproto.Type type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.edu.umn.cse.geoproto.Type type = 1;</code>
       */
      public edu.umn.cse.geoproto.GeoProto.Type getType() {
        edu.umn.cse.geoproto.GeoProto.Type result = edu.umn.cse.geoproto.GeoProto.Type.valueOf(type_);
        return result == null ? edu.umn.cse.geoproto.GeoProto.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.edu.umn.cse.geoproto.Type type = 1;</code>
       */
      public Builder setType(edu.umn.cse.geoproto.GeoProto.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.edu.umn.cse.geoproto.Type type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private edu.umn.cse.geoproto.GeoProto.GeometryMsg geometry_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          edu.umn.cse.geoproto.GeoProto.GeometryMsg, edu.umn.cse.geoproto.GeoProto.GeometryMsg.Builder, edu.umn.cse.geoproto.GeoProto.GeometryMsgOrBuilder> geometryBuilder_;
      /**
       * <code>.edu.umn.cse.geoproto.GeometryMsg geometry = 2;</code>
       */
      public boolean hasGeometry() {
        return geometryBuilder_ != null || geometry_ != null;
      }
      /**
       * <code>.edu.umn.cse.geoproto.GeometryMsg geometry = 2;</code>
       */
      public edu.umn.cse.geoproto.GeoProto.GeometryMsg getGeometry() {
        if (geometryBuilder_ == null) {
          return geometry_ == null ? edu.umn.cse.geoproto.GeoProto.GeometryMsg.getDefaultInstance() : geometry_;
        } else {
          return geometryBuilder_.getMessage();
        }
      }
      /**
       * <code>.edu.umn.cse.geoproto.GeometryMsg geometry = 2;</code>
       */
      public Builder setGeometry(edu.umn.cse.geoproto.GeoProto.GeometryMsg value) {
        if (geometryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          geometry_ = value;
          onChanged();
        } else {
          geometryBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.edu.umn.cse.geoproto.GeometryMsg geometry = 2;</code>
       */
      public Builder setGeometry(
          edu.umn.cse.geoproto.GeoProto.GeometryMsg.Builder builderForValue) {
        if (geometryBuilder_ == null) {
          geometry_ = builderForValue.build();
          onChanged();
        } else {
          geometryBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.edu.umn.cse.geoproto.GeometryMsg geometry = 2;</code>
       */
      public Builder mergeGeometry(edu.umn.cse.geoproto.GeoProto.GeometryMsg value) {
        if (geometryBuilder_ == null) {
          if (geometry_ != null) {
            geometry_ =
              edu.umn.cse.geoproto.GeoProto.GeometryMsg.newBuilder(geometry_).mergeFrom(value).buildPartial();
          } else {
            geometry_ = value;
          }
          onChanged();
        } else {
          geometryBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.edu.umn.cse.geoproto.GeometryMsg geometry = 2;</code>
       */
      public Builder clearGeometry() {
        if (geometryBuilder_ == null) {
          geometry_ = null;
          onChanged();
        } else {
          geometry_ = null;
          geometryBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.edu.umn.cse.geoproto.GeometryMsg geometry = 2;</code>
       */
      public edu.umn.cse.geoproto.GeoProto.GeometryMsg.Builder getGeometryBuilder() {
        
        onChanged();
        return getGeometryFieldBuilder().getBuilder();
      }
      /**
       * <code>.edu.umn.cse.geoproto.GeometryMsg geometry = 2;</code>
       */
      public edu.umn.cse.geoproto.GeoProto.GeometryMsgOrBuilder getGeometryOrBuilder() {
        if (geometryBuilder_ != null) {
          return geometryBuilder_.getMessageOrBuilder();
        } else {
          return geometry_ == null ?
              edu.umn.cse.geoproto.GeoProto.GeometryMsg.getDefaultInstance() : geometry_;
        }
      }
      /**
       * <code>.edu.umn.cse.geoproto.GeometryMsg geometry = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          edu.umn.cse.geoproto.GeoProto.GeometryMsg, edu.umn.cse.geoproto.GeoProto.GeometryMsg.Builder, edu.umn.cse.geoproto.GeoProto.GeometryMsgOrBuilder> 
          getGeometryFieldBuilder() {
        if (geometryBuilder_ == null) {
          geometryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              edu.umn.cse.geoproto.GeoProto.GeometryMsg, edu.umn.cse.geoproto.GeoProto.GeometryMsg.Builder, edu.umn.cse.geoproto.GeoProto.GeometryMsgOrBuilder>(
                  getGeometry(),
                  getParentForChildren(),
                  isClean());
          geometry_ = null;
        }
        return geometryBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> properties_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetProperties() {
        if (properties_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              PropertiesDefaultEntryHolder.defaultEntry);
        }
        return properties_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableProperties() {
        onChanged();;
        if (properties_ == null) {
          properties_ = com.google.protobuf.MapField.newMapField(
              PropertiesDefaultEntryHolder.defaultEntry);
        }
        if (!properties_.isMutable()) {
          properties_ = properties_.copy();
        }
        return properties_;
      }

      public int getPropertiesCount() {
        return internalGetProperties().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; properties = 3;</code>
       */

      public boolean containsProperties(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetProperties().getMap().containsKey(key);
      }
      /**
       * Use {@link #getPropertiesMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getProperties() {
        return getPropertiesMap();
      }
      /**
       * <code>map&lt;string, string&gt; properties = 3;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getPropertiesMap() {
        return internalGetProperties().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; properties = 3;</code>
       */

      public java.lang.String getPropertiesOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetProperties().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; properties = 3;</code>
       */

      public java.lang.String getPropertiesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetProperties().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearProperties() {
        internalGetMutableProperties().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; properties = 3;</code>
       */

      public Builder removeProperties(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableProperties().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableProperties() {
        return internalGetMutableProperties().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; properties = 3;</code>
       */
      public Builder putProperties(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableProperties().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; properties = 3;</code>
       */

      public Builder putAllProperties(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableProperties().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:edu.umn.cse.geoproto.FeatureMsg)
    }

    // @@protoc_insertion_point(class_scope:edu.umn.cse.geoproto.FeatureMsg)
    private static final edu.umn.cse.geoproto.GeoProto.FeatureMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.umn.cse.geoproto.GeoProto.FeatureMsg();
    }

    public static edu.umn.cse.geoproto.GeoProto.FeatureMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FeatureMsg>
        PARSER = new com.google.protobuf.AbstractParser<FeatureMsg>() {
      public FeatureMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FeatureMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FeatureMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FeatureMsg> getParserForType() {
      return PARSER;
    }

    public edu.umn.cse.geoproto.GeoProto.FeatureMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GeometryMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:edu.umn.cse.geoproto.GeometryMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.edu.umn.cse.geoproto.GeometryType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.edu.umn.cse.geoproto.GeometryType type = 1;</code>
     */
    edu.umn.cse.geoproto.GeoProto.GeometryType getType();

    /**
     * <code>repeated double coordinates = 2;</code>
     */
    java.util.List<java.lang.Double> getCoordinatesList();
    /**
     * <code>repeated double coordinates = 2;</code>
     */
    int getCoordinatesCount();
    /**
     * <code>repeated double coordinates = 2;</code>
     */
    double getCoordinates(int index);
  }
  /**
   * Protobuf type {@code edu.umn.cse.geoproto.GeometryMsg}
   */
  public  static final class GeometryMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:edu.umn.cse.geoproto.GeometryMsg)
      GeometryMsgOrBuilder {
    // Use GeometryMsg.newBuilder() to construct.
    private GeometryMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GeometryMsg() {
      type_ = 0;
      coordinates_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GeometryMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 17: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                coordinates_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000002;
              }
              coordinates_.add(input.readDouble());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                coordinates_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                coordinates_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          coordinates_ = java.util.Collections.unmodifiableList(coordinates_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umn.cse.geoproto.GeoProto.internal_static_edu_umn_cse_geoproto_GeometryMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umn.cse.geoproto.GeoProto.internal_static_edu_umn_cse_geoproto_GeometryMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.umn.cse.geoproto.GeoProto.GeometryMsg.class, edu.umn.cse.geoproto.GeoProto.GeometryMsg.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.edu.umn.cse.geoproto.GeometryType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.edu.umn.cse.geoproto.GeometryType type = 1;</code>
     */
    public edu.umn.cse.geoproto.GeoProto.GeometryType getType() {
      edu.umn.cse.geoproto.GeoProto.GeometryType result = edu.umn.cse.geoproto.GeoProto.GeometryType.valueOf(type_);
      return result == null ? edu.umn.cse.geoproto.GeoProto.GeometryType.UNRECOGNIZED : result;
    }

    public static final int COORDINATES_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Double> coordinates_;
    /**
     * <code>repeated double coordinates = 2;</code>
     */
    public java.util.List<java.lang.Double>
        getCoordinatesList() {
      return coordinates_;
    }
    /**
     * <code>repeated double coordinates = 2;</code>
     */
    public int getCoordinatesCount() {
      return coordinates_.size();
    }
    /**
     * <code>repeated double coordinates = 2;</code>
     */
    public double getCoordinates(int index) {
      return coordinates_.get(index);
    }
    private int coordinatesMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (type_ != edu.umn.cse.geoproto.GeoProto.GeometryType.Point.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (getCoordinatesList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(coordinatesMemoizedSerializedSize);
      }
      for (int i = 0; i < coordinates_.size(); i++) {
        output.writeDoubleNoTag(coordinates_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != edu.umn.cse.geoproto.GeoProto.GeometryType.Point.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      {
        int dataSize = 0;
        dataSize = 8 * getCoordinatesList().size();
        size += dataSize;
        if (!getCoordinatesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        coordinatesMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.umn.cse.geoproto.GeoProto.GeometryMsg)) {
        return super.equals(obj);
      }
      edu.umn.cse.geoproto.GeoProto.GeometryMsg other = (edu.umn.cse.geoproto.GeoProto.GeometryMsg) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getCoordinatesList()
          .equals(other.getCoordinatesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (getCoordinatesCount() > 0) {
        hash = (37 * hash) + COORDINATES_FIELD_NUMBER;
        hash = (53 * hash) + getCoordinatesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.umn.cse.geoproto.GeoProto.GeometryMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umn.cse.geoproto.GeoProto.GeometryMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umn.cse.geoproto.GeoProto.GeometryMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umn.cse.geoproto.GeoProto.GeometryMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umn.cse.geoproto.GeoProto.GeometryMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.umn.cse.geoproto.GeoProto.GeometryMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.umn.cse.geoproto.GeoProto.GeometryMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.umn.cse.geoproto.GeoProto.GeometryMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.umn.cse.geoproto.GeoProto.GeometryMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.umn.cse.geoproto.GeoProto.GeometryMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.umn.cse.geoproto.GeoProto.GeometryMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu.umn.cse.geoproto.GeometryMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:edu.umn.cse.geoproto.GeometryMsg)
        edu.umn.cse.geoproto.GeoProto.GeometryMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.umn.cse.geoproto.GeoProto.internal_static_edu_umn_cse_geoproto_GeometryMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.umn.cse.geoproto.GeoProto.internal_static_edu_umn_cse_geoproto_GeometryMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.umn.cse.geoproto.GeoProto.GeometryMsg.class, edu.umn.cse.geoproto.GeoProto.GeometryMsg.Builder.class);
      }

      // Construct using edu.umn.cse.geoproto.GeoProto.GeometryMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        coordinates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umn.cse.geoproto.GeoProto.internal_static_edu_umn_cse_geoproto_GeometryMsg_descriptor;
      }

      public edu.umn.cse.geoproto.GeoProto.GeometryMsg getDefaultInstanceForType() {
        return edu.umn.cse.geoproto.GeoProto.GeometryMsg.getDefaultInstance();
      }

      public edu.umn.cse.geoproto.GeoProto.GeometryMsg build() {
        edu.umn.cse.geoproto.GeoProto.GeometryMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.umn.cse.geoproto.GeoProto.GeometryMsg buildPartial() {
        edu.umn.cse.geoproto.GeoProto.GeometryMsg result = new edu.umn.cse.geoproto.GeoProto.GeometryMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          coordinates_ = java.util.Collections.unmodifiableList(coordinates_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.coordinates_ = coordinates_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umn.cse.geoproto.GeoProto.GeometryMsg) {
          return mergeFrom((edu.umn.cse.geoproto.GeoProto.GeometryMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.umn.cse.geoproto.GeoProto.GeometryMsg other) {
        if (other == edu.umn.cse.geoproto.GeoProto.GeometryMsg.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.coordinates_.isEmpty()) {
          if (coordinates_.isEmpty()) {
            coordinates_ = other.coordinates_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureCoordinatesIsMutable();
            coordinates_.addAll(other.coordinates_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.umn.cse.geoproto.GeoProto.GeometryMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.umn.cse.geoproto.GeoProto.GeometryMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.edu.umn.cse.geoproto.GeometryType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.edu.umn.cse.geoproto.GeometryType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.edu.umn.cse.geoproto.GeometryType type = 1;</code>
       */
      public edu.umn.cse.geoproto.GeoProto.GeometryType getType() {
        edu.umn.cse.geoproto.GeoProto.GeometryType result = edu.umn.cse.geoproto.GeoProto.GeometryType.valueOf(type_);
        return result == null ? edu.umn.cse.geoproto.GeoProto.GeometryType.UNRECOGNIZED : result;
      }
      /**
       * <code>.edu.umn.cse.geoproto.GeometryType type = 1;</code>
       */
      public Builder setType(edu.umn.cse.geoproto.GeoProto.GeometryType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.edu.umn.cse.geoproto.GeometryType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Double> coordinates_ = java.util.Collections.emptyList();
      private void ensureCoordinatesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          coordinates_ = new java.util.ArrayList<java.lang.Double>(coordinates_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated double coordinates = 2;</code>
       */
      public java.util.List<java.lang.Double>
          getCoordinatesList() {
        return java.util.Collections.unmodifiableList(coordinates_);
      }
      /**
       * <code>repeated double coordinates = 2;</code>
       */
      public int getCoordinatesCount() {
        return coordinates_.size();
      }
      /**
       * <code>repeated double coordinates = 2;</code>
       */
      public double getCoordinates(int index) {
        return coordinates_.get(index);
      }
      /**
       * <code>repeated double coordinates = 2;</code>
       */
      public Builder setCoordinates(
          int index, double value) {
        ensureCoordinatesIsMutable();
        coordinates_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double coordinates = 2;</code>
       */
      public Builder addCoordinates(double value) {
        ensureCoordinatesIsMutable();
        coordinates_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double coordinates = 2;</code>
       */
      public Builder addAllCoordinates(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureCoordinatesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, coordinates_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double coordinates = 2;</code>
       */
      public Builder clearCoordinates() {
        coordinates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:edu.umn.cse.geoproto.GeometryMsg)
    }

    // @@protoc_insertion_point(class_scope:edu.umn.cse.geoproto.GeometryMsg)
    private static final edu.umn.cse.geoproto.GeoProto.GeometryMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.umn.cse.geoproto.GeoProto.GeometryMsg();
    }

    public static edu.umn.cse.geoproto.GeoProto.GeometryMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GeometryMsg>
        PARSER = new com.google.protobuf.AbstractParser<GeometryMsg>() {
      public GeometryMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GeometryMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GeometryMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GeometryMsg> getParserForType() {
      return PARSER;
    }

    public edu.umn.cse.geoproto.GeoProto.GeometryMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_umn_cse_geoproto_FeatureCollectionMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_umn_cse_geoproto_FeatureCollectionMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_umn_cse_geoproto_FeatureMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_umn_cse_geoproto_FeatureMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_umn_cse_geoproto_FeatureMsg_PropertiesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_umn_cse_geoproto_FeatureMsg_PropertiesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_umn_cse_geoproto_GeometryMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_umn_cse_geoproto_GeometryMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017geo-proto.proto\022\024edu.umn.cse.geoproto\"" +
      "t\n\024FeatureCollectionMsg\022(\n\004type\030\001 \001(\0162\032." +
      "edu.umn.cse.geoproto.Type\0222\n\010features\030\002 " +
      "\003(\0132 .edu.umn.cse.geoproto.FeatureMsg\"\344\001" +
      "\n\nFeatureMsg\022(\n\004type\030\001 \001(\0162\032.edu.umn.cse" +
      ".geoproto.Type\0223\n\010geometry\030\002 \001(\0132!.edu.u" +
      "mn.cse.geoproto.GeometryMsg\022D\n\npropertie" +
      "s\030\003 \003(\01320.edu.umn.cse.geoproto.FeatureMs" +
      "g.PropertiesEntry\0321\n\017PropertiesEntry\022\013\n\003" +
      "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"T\n\013Geometry",
      "Msg\0220\n\004type\030\001 \001(\0162\".edu.umn.cse.geoproto" +
      ".GeometryType\022\023\n\013coordinates\030\002 \003(\001*8\n\004Ty" +
      "pe\022\025\n\021FeatureCollection\020\000\022\013\n\007Feature\020\001\022\014" +
      "\n\010Geometry\020\002*\205\001\n\014GeometryType\022\t\n\005Point\020\000" +
      "\022\016\n\nLineString\020\001\022\013\n\007Polygon\020\002\022\016\n\nMultiPo" +
      "int\020\003\022\023\n\017MultiLineString\020\004\022\020\n\014MultiPolyg" +
      "on\020\005\022\026\n\022GeometryCollection\020\006b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_edu_umn_cse_geoproto_FeatureCollectionMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_edu_umn_cse_geoproto_FeatureCollectionMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_umn_cse_geoproto_FeatureCollectionMsg_descriptor,
        new java.lang.String[] { "Type", "Features", });
    internal_static_edu_umn_cse_geoproto_FeatureMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_edu_umn_cse_geoproto_FeatureMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_umn_cse_geoproto_FeatureMsg_descriptor,
        new java.lang.String[] { "Type", "Geometry", "Properties", });
    internal_static_edu_umn_cse_geoproto_FeatureMsg_PropertiesEntry_descriptor =
      internal_static_edu_umn_cse_geoproto_FeatureMsg_descriptor.getNestedTypes().get(0);
    internal_static_edu_umn_cse_geoproto_FeatureMsg_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_umn_cse_geoproto_FeatureMsg_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_edu_umn_cse_geoproto_GeometryMsg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_edu_umn_cse_geoproto_GeometryMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_umn_cse_geoproto_GeometryMsg_descriptor,
        new java.lang.String[] { "Type", "Coordinates", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
